export const loginUser = JSON.parse(sessionStorage.getItem("user"));

const friends = () => [
  {
    name: "WuSeLeWu",
    username: "wuselewu",
    status: "bosta",
    profilePicture: "baby.jpg",
    password: "wuse1",
    IsSee: "admin",
  },
  {
    name: "Eren Agr",
    username: "erenagr",
    status: "cevrimici",
    profilePicture: "eren.jpg",
    password: "1",
    IsSee: "sidebar",
  },
  {
    name: "Hakan",
    username: "hakancyln",
    status: "cevrimdisi",
    profilePicture: "profile.jpg",
    password: "1",
    IsSee: "sidebar",
  },
  {
    name: "Onur",
    username: "odinc",
    status: "cevrimdisi",
    profilePicture: "deadpool.jpg",
    password: "1",
    IsSee: "sidebar",
  },
  {
    name: "Emirhan",
    username: "ecinci",
    status: "cevrimdisi",
    profilePicture: "ghost.jpg",
    password: "1",
    IsSee: "sidebar",
  },
  {
    name: "Bilal",
    username: "bilal-captain19",
    status: "cevrimici",
    profilePicture: "bilal.jpg",
    password: "1",
    IsSee: "all",
  },
  {
    name: "Eyyüp",
    username: "eyp.kndrc",
    status: "bosta",
    profilePicture: "eyup.jpg",
    password: "1",
    IsSee: "all",
  },
  {
    name: "Fatih",
    username: "fsarman",
    status: "bosta",
    profilePicture: "fatih.png",
    password: "1",
    IsSee: "all",
  },
  {
    name: "Ömer",
    username: "ömrSrlvk",
    status: "cevrimdisi",
    profilePicture: "images.jpg",
    password: "1",
    IsSee: "all",
  },
  {
    name: "Eray Amca",
    username: "amca31",
    status: "bosta",
    profilePicture: "ıronman.jpg",
    password: "1",
    IsSee: "all",
  },
  {
    name: "Enes Dede",
    username: "dedem29",
    status: "cevrimdisi",
    profilePicture: "joker.jpg",
    password: "1",
    IsSee: "all",
  },
];

export default friends;
